### ISSUE TITLE
godaddy解析问题

### ISSUE THREAD

**Issue by XTeam-Wing** [AbelChe/cola_dnslog#14]
godaddy设置自定义域名服务器之后，就无法继续修改DNS记录。
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/25416365/187588124-c0511ac9-f0d0-4af2-983f-1c4e60a8c2f1.png">

**Comment by AbelChe** [comment]
当然不可以，这样就对了。
因为你已经将域名服务器指向了非godaddy官方服务器

**Comment by XTeam-Wing** [comment]
阿里云设置方便，但是国内注册的非备案域名只能用国外IP。
