### ISSUE TITLE
docker一键部署，如何联动钉钉机器人，在说明文档中没找到命令行版

### ISSUE THREAD

**Issue by hackfox666** [AbelChe/cola_dnslog#15]

**Comment by AbelChe** [comment]
docker一件部署已经写的很详细了，先下载源码，修改配置文件，然后使用docker-compose启动即可：[https://github.com/AbelChe/cola_dnslog#一键启动推荐](https://github.com/AbelChe/cola_dnslog#一键启动推荐)

联动钉钉机器人，文档中也有详细的描述：[https://github.com/AbelChe/cola_dnslog#钉钉机器人](https://github.com/AbelChe/cola_dnslog#钉钉机器人)
