### ISSUE TITLE
一直卡在这里不动

### ISSUE THREAD

**Issue by xyongsec** [AbelChe/cola_dnslog#16]
![image](https://user-images.githubusercontent.com/48509164/190947130-ae9344ee-cada-40ad-bf8f-4a5044aaeb26.png)

**Comment by xyongsec** [comment]
![image](https://user-images.githubusercontent.com/48509164/190947173-cfd175db-0e50-44d3-9a6d-4f3410badbf8.png)

**Comment by AbelChe** [comment]
npm从github下载相关依赖，国内的vps封github的，上github要看运气的
我尝试过很多方法，包括使用cnpm、换源、改hosts等，很不幸的是，这些都无法流畅的通过npm install
目前除了换网络通畅地区的vps，暂时没有什么好的解决方案。。。
