### ISSUE TITLE
多个问题

### ISSUE THREAD

**Issue by cqrlhz** [AbelChe/cola_dnslog#18]
问题：
1、修改docker-compose.yml配置文件httplog 服务为非80端口启动后依然是80无法修改端口
2、httplog服务非常容易死 ubuntu 20 版本下httplog服务可能安装后正常十分钟，十分钟后查看80端口已关闭，需重启容器恢复，十分钟左右又死.....
3、海外vps在dns服务模块不知道网络原因还是其他原因比如：ping 10次 只有一二次能解析成功

**Comment by AbelChe** [comment]
感谢反馈，之后会陆续修复
