### ISSUE TITLE
logserrver服务几分钟之后必死，报错信息：./start_logserver: line 9:   377 Segmentation fault      (core dumped) python server.py

### ISSUE THREAD

**Issue by cqrlhz** [AbelChe/cola_dnslog#19]
报错信息：./start_logserver: line 9:   377 Segmentation fault      (core dumped) python server.py

**Comment by AbelChe** [comment]
感谢反馈，是有这个问题。
忙完这阵，之后和其他问题统一修复

**Comment by AbelChe** [comment]
> 报错信息：./start_logserver: line 9: 377 Segmentation fault (core dumped) python server.py

原因：并发过高，导致单线程写入数据库崩溃
已解决，1.3.2版本修复
