### ISSUE TITLE
疑似start_logserevr名称错误导致httplog无回显

### ISSUE THREAD

**Issue by Zh9ng9** [AbelChe/cola_dnslog#7]
部署完成后发现httplog无回显，将错误拼写的start_logserevr名称更正之后服务正常。
`mv ./start_logserevr ./start_logserver`
猜测是拼写错误导致

**Comment by AbelChe** [comment]
文件名的确拼写有错误，但是并不影响功能使用
v1.2.3 文件名拼写错误已修复
